name: Develop Branch

permissions:
  id-token: write
  contents: read

on:
  push:
    branches-ignore:
      - "main"
      - "dependabot/**"
      - "temp-*"
      - "hotfix-*"

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Check Code Style
        run: mvn checkstyle:check

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Run Tests
        run: mvn test

  deploy:
    needs:
      - check-code
      - run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Deploy
        run: mvn deploy